// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Dominion.Specs.Cards
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Adventurer")]
    public partial class AdventurerFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Adventurer.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Adventurer", "", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Play Adventurer but reveal no treasure")]
        public virtual void PlayAdventurerButRevealNoTreasure()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Play Adventurer but reveal no treasure", ((string[])(null)));
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
testRunner.Given("A new game with 3 players");
#line 5
testRunner.And("Player1 has a hand of Adventurer, Copper, Copper, Copper, Copper");
#line 6
testRunner.And("Player1 has a deck of Estate, Estate, Estate, Estate, Estate");
#line 7
testRunner.When("Player1 plays a Adventurer");
#line 8
testRunner.Then("Player1 should have a hand of Copper, Copper, Copper, Copper");
#line 9
testRunner.And("Player1 should have 0 cards in deck");
#line 10
testRunner.And("Player1 should have a discard pile of Estate, Estate, Estate, Estate, Estate");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Play Adventurer but reveal only one treasure")]
        public virtual void PlayAdventurerButRevealOnlyOneTreasure()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Play Adventurer but reveal only one treasure", ((string[])(null)));
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
testRunner.Given("A new game with 3 players");
#line 14
testRunner.And("Player1 has a hand of Adventurer, Copper, Copper, Copper, Copper");
#line 15
testRunner.And("Player1 has a deck of Estate, Estate, Estate, Copper, Estate");
#line 16
testRunner.When("Player1 plays a Adventurer");
#line 17
testRunner.Then("Player1 should have a hand of Copper, Copper, Copper, Copper, Copper");
#line 18
testRunner.And("Player1 should have 0 cards in deck");
#line 19
testRunner.And("Player1 should have a discard pile of Estate, Estate, Estate, Estate");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Play Adventurer and reveal two treasure")]
        public virtual void PlayAdventurerAndRevealTwoTreasure()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Play Adventurer and reveal two treasure", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
testRunner.Given("A new game with 3 players");
#line 23
testRunner.And("Player1 has a hand of Adventurer, Copper, Copper, Copper, Copper");
#line 24
testRunner.And("Player1 has a deck of Estate, Copper, Estate, Copper, Silver");
#line 25
testRunner.When("Player1 plays a Adventurer");
#line 26
testRunner.Then("Player1 should have a hand of Copper, Copper, Copper, Copper, Copper, Copper");
#line 27
testRunner.And("Player1 should have a deck of: Silver");
#line 28
testRunner.And("Player1 should have a discard pile of Estate, Estate");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
