// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Dominion.Specs.Cards
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Baron")]
    public partial class BaronFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Baron.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Baron", "", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player plays baron with no estate in hand")]
        public virtual void PlayerPlaysBaronWithNoEstateInHand()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player plays baron with no estate in hand", ((string[])(null)));
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
testRunner.Given("A new game with 3 players");
#line 5
testRunner.And("Player1 has a hand of Baron, Copper, Copper, Copper, Copper");
#line 6
testRunner.When("Player1 plays a Baron");
#line 7
testRunner.Then("Player1 should have an Estate on top of the discard pile");
#line 8
testRunner.And("Player1 should have 2 buys");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player plays baron with an estate in hand and must choose")]
        public virtual void PlayerPlaysBaronWithAnEstateInHandAndMustChoose()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player plays baron with an estate in hand and must choose", ((string[])(null)));
#line 10
this.ScenarioSetup(scenarioInfo);
#line 11
testRunner.Given("A new game with 3 players");
#line 12
testRunner.And("Player1 has a hand of Baron, Estate, Copper, Copper, Copper");
#line 13
testRunner.When("Player1 plays a Baron");
#line 14
testRunner.Then("Player1 must choose whether to use Chancellor\'s effect (Yes or No)");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player plays baron with an estate in hand and chooses to discard it")]
        public virtual void PlayerPlaysBaronWithAnEstateInHandAndChoosesToDiscardIt()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player plays baron with an estate in hand and chooses to discard it", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
testRunner.Given("A new game with 3 players");
#line 18
testRunner.And("Player1 has a hand of Baron, Estate, Copper, Copper, Copper");
#line 19
testRunner.When("Player1 plays a Baron");
#line 20
testRunner.When("Player1 chooses to discard the estate (Yes)");
#line 21
testRunner.Then("Player1 should have 4 to spend");
#line 22
testRunner.Then("Player1 should have an Estate on top of the discard pile");
#line 23
testRunner.And("Player1 should have a hand of Copper, Copper, Copper");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player plays baron with an estate in hand and chooses not to discard")]
        public virtual void PlayerPlaysBaronWithAnEstateInHandAndChoosesNotToDiscard()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player plays baron with an estate in hand and chooses not to discard", ((string[])(null)));
#line 25
this.ScenarioSetup(scenarioInfo);
#line 26
testRunner.Given("A new game with 3 players");
#line 27
testRunner.And("Player1 has a hand of Baron, Estate, Copper, Copper, Copper");
#line 28
testRunner.When("Player1 plays a Baron");
#line 29
testRunner.When("Player1 chooses to keep the estate (No)");
#line 30
testRunner.Then("Player1 should have 0 to spend");
#line 31
testRunner.And("Player1 should have an Estate on top of the discard pile");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
