// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Dominion.Specs.Cards
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Explorer")]
    public partial class ExplorerFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Explorer.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Explorer", "", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player must decide whether to reveal province after playing explorer")]
        public virtual void PlayerMustDecideWhetherToRevealProvinceAfterPlayingExplorer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player must decide whether to reveal province after playing explorer", ((string[])(null)));
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
testRunner.Given("A new game with 3 players");
#line 5
testRunner.And("Player1 has a hand of Explorer, Province, Copper, Copper, Estate");
#line 6
testRunner.When("Player1 plays an Explorer");
#line 7
testRunner.Then("Player1 must choose whether to reveal a Province (Yes or No)");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player reveals a province and gains a gold")]
        public virtual void PlayerRevealsAProvinceAndGainsAGold()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player reveals a province and gains a gold", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
testRunner.Given("A new game with 3 players");
#line 11
testRunner.And("Player1 has a hand of Explorer, Province, Copper, Copper, Estate");
#line 12
testRunner.When("Player1 plays an Explorer");
#line 13
testRunner.And("Player1 chooses to gain a Gold (Yes)");
#line 14
testRunner.Then("Player1 should have a hand of Province, Copper, Copper, Estate, Gold");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player chooses not to reveal a province and gains a silver")]
        public virtual void PlayerChoosesNotToRevealAProvinceAndGainsASilver()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player chooses not to reveal a province and gains a silver", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
testRunner.Given("A new game with 3 players");
#line 18
testRunner.And("Player1 has a hand of Explorer, Province, Copper, Copper, Estate");
#line 19
testRunner.When("Player1 plays an Explorer");
#line 20
testRunner.And("Player1 chooses to gain a Silver (No)");
#line 21
testRunner.Then("Player1 should have a hand of Province, Copper, Copper, Estate, Silver");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player does not have a Province in hand and gains a silver")]
        public virtual void PlayerDoesNotHaveAProvinceInHandAndGainsASilver()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player does not have a Province in hand and gains a silver", ((string[])(null)));
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
testRunner.Given("A new game with 3 players");
#line 25
testRunner.And("Player1 has a hand of Explorer, Estate, Copper, Copper, Estate");
#line 26
testRunner.When("Player1 plays an Explorer");
#line 27
testRunner.Then("All actions should be resolved");
#line 28
testRunner.And("Player1 should have a hand of Estate, Copper, Copper, Estate, Silver");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
