// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Dominion.Specs.Cards
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Mountebank")]
    public partial class MountebankFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Mountebank.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Mountebank", "", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player plays Mountebank when opponents have no curses in hand")]
        public virtual void PlayerPlaysMountebankWhenOpponentsHaveNoCursesInHand()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player plays Mountebank when opponents have no curses in hand", ((string[])(null)));
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
testRunner.Given("A new game with 3 players");
#line 5
testRunner.And("Player1 has a Mountebank in hand instead of a Copper");
#line 6
testRunner.When("Player1 plays a Mountebank");
#line 7
testRunner.Then("Player1 should have 2 to spend");
#line 8
testRunner.Then("Player2 should have a discard pile of Copper, Curse");
#line 9
testRunner.Then("Player3 should have a discard pile of Copper, Curse");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player plays Mountebank, opponent must choose whether to discard a curse")]
        public virtual void PlayerPlaysMountebankOpponentMustChooseWhetherToDiscardACurse()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player plays Mountebank, opponent must choose whether to discard a curse", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line 12
testRunner.Given("A new game with 3 players");
#line 13
testRunner.And("Player1 has a Mountebank in hand instead of a Copper");
#line 14
testRunner.And("Player2 has a Curse in hand instead of a Copper");
#line 15
testRunner.When("Player1 plays a Mountebank");
#line 16
testRunner.Then("Player2 must choose whether to discard a Curse (Yes or No)");
#line 17
testRunner.Then("Player3 must wait");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Play Mountebank when an opponent is holding a curse")]
        public virtual void PlayMountebankWhenAnOpponentIsHoldingACurse()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Play Mountebank when an opponent is holding a curse", ((string[])(null)));
#line 19
this.ScenarioSetup(scenarioInfo);
#line 20
testRunner.Given("A new game with 3 players");
#line 21
testRunner.And("Player1 has a Mountebank in hand instead of a Copper");
#line 22
testRunner.And("Player2 has a Curse in hand instead of a Copper");
#line 23
testRunner.When("Player1 plays a Mountebank");
#line 24
testRunner.When("Player2 chooses to discard a Curse (Yes)");
#line 25
testRunner.Then("Player2 should have a discard pile of Curse");
#line 26
testRunner.Then("Player3 should have a discard pile of Copper, Curse");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
