// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Dominion.Specs.Cards
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Salvager")]
    public partial class SalvagerFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Salvager.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Salvager", "", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Salvager trashes a card")]
        public virtual void SalvagerTrashesACard()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Salvager trashes a card", ((string[])(null)));
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
testRunner.Given("A new game with 3 players");
#line 5
testRunner.And("Player1 has a Salvager in hand instead of a Copper");
#line 6
testRunner.And("Player1 has a Salvager in hand instead of a Copper");
#line 7
testRunner.When("Player1 plays a Salvager");
#line 8
testRunner.Then("Player1 must select 1 card to trash");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Salvager trashing estate gives plus 2 spend")]
        public virtual void SalvagerTrashingEstateGivesPlus2Spend()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Salvager trashing estate gives plus 2 spend", ((string[])(null)));
#line 10
this.ScenarioSetup(scenarioInfo);
#line 11
testRunner.Given("A new game with 3 players");
#line 12
testRunner.And("Player1 has a Salvager in hand instead of a Copper");
#line 13
testRunner.And("Player1 has a Salvager in hand instead of a Copper");
#line 14
testRunner.When("Player1 plays a Salvager");
#line 15
testRunner.And("Player1 selects a Estate to trash");
#line 16
testRunner.Then("Player1 should have 2 to spend");
#line 17
testRunner.And("Player1 should have 2 buys");
#line 18
testRunner.And("There should be a Estate on top of the trash pile");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Salvager with no other cards in hand")]
        public virtual void SalvagerWithNoOtherCardsInHand()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Salvager with no other cards in hand", ((string[])(null)));
#line 20
this.ScenarioSetup(scenarioInfo);
#line 21
testRunner.Given("A new game with 3 players");
#line 22
testRunner.And("Player1 has a hand of Salvager");
#line 23
testRunner.When("Player1 plays a Salvager");
#line 24
testRunner.Then("All actions should be resolved");
#line 25
testRunner.And("Player1 should have 2 buys");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Salvaging a potion card does not let the player buy a potion card")]
        public virtual void SalvagingAPotionCardDoesNotLetThePlayerBuyAPotionCard()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Salvaging a potion card does not let the player buy a potion card", ((string[])(null)));
#line 27
this.ScenarioSetup(scenarioInfo);
#line 28
testRunner.Given("A new game with 3 players");
#line 29
testRunner.And("Player1 has a hand of Salvager, Golem, Estate, Estate, Estate");
#line 30
testRunner.When("Player1 plays a Salvager");
#line 31
testRunner.And("Player1 selects a Golem to trash");
#line 32
testRunner.Then("Player1 should have 4 to spend");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
