// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Dominion.Specs.Cards
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Treasure Map")]
    public partial class TreasureMapFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TreasureMap.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Treasure Map", "", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Playing treasure map with another treasure map in hand gets the gold")]
        public virtual void PlayingTreasureMapWithAnotherTreasureMapInHandGetsTheGold()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Playing treasure map with another treasure map in hand gets the gold", ((string[])(null)));
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
testRunner.Given("A new game with 3 players");
#line 5
testRunner.And("Player1 has a hand of TreasureMap, TreasureMap, Copper, Copper, Estate");
#line 6
testRunner.And("Player1 has a deck of Estate, Copper, Copper, Copper, Estate");
#line 7
testRunner.When("Player1 plays a TreasureMap");
#line 8
testRunner.Then("The trash pile should be TreasureMap, TreasureMap");
#line 9
testRunner.And("Player1 should have a deck of: Gold, Gold, Gold, Gold, Estate, Copper, Copper, Co" +
                    "pper, Estate");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Playing treasure map without another one in hand just trashes it")]
        public virtual void PlayingTreasureMapWithoutAnotherOneInHandJustTrashesIt()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Playing treasure map without another one in hand just trashes it", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line 12
testRunner.Given("A new game with 3 players");
#line 13
testRunner.And("Player1 has a hand of TreasureMap, Copper, Copper, Copper, Estate");
#line 14
testRunner.And("Player1 has a deck of Estate, Copper, Copper, Copper, Estate");
#line 15
testRunner.When("Player1 plays a TreasureMap");
#line 16
testRunner.Then("The trash pile should be TreasureMap");
#line 17
testRunner.And("Player1 should have a deck of: Estate, Copper, Copper, Copper, Estate");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
